name: TFM_project_env
channels:
  - conda-forge
  - bioconda
  - defaults
channel_priority: strict
dependencies:
  - python=3.10
  - fastqc=0.11.9
  - trimmomatic=0.39
  - bowtie2=2.5.4
  - htseq=2.0.5
  - kraken2=2.1.3
  - samtools=1.21
